In [6]:
import numpy as np

   ### Задание 1

In [14]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Задание 2

In [18]:
b1 = a.reshape(3,4)
b1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
b2 = a.reshape(6,2)
b2

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [22]:
b3 = a.reshape(4,3)
b3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [31]:
b4 = a.reshape(2,6)
b4

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### Задание 4

In [32]:
#Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
#да