In [5]:
import numpy as np

In [6]:
a = np.array([[1, 2, 3, 3, 1],
              [6, 8, 11, 10, 7]])

In [7]:
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [8]:
b =  np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])

In [9]:
b

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

        ЗАДАНИЕ 1

In [17]:
mean_a = np.mean(b,axis=0)
mean_a

array([2. , 8.4])

       Задание 2

In [14]:
a_centered = b-mean_a

In [16]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

        Задание 3

In [21]:
x1 = np.hsplit(a_centered,2)

In [25]:
a_centered_sp = x1[0]*x1[1]

In [26]:
a_centered_sp

array([[ 2.4],
       [-0. ],
       [ 2.6],
       [ 1.6],
       [ 1.4]])

In [27]:
a_centered_sp/4

array([[ 0.6 ],
       [-0.  ],
       [ 0.65],
       [ 0.4 ],
       [ 0.35]])